name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check for missing files and add them
      run: |
        if ! test -f Makefile.in; then
          echo "Makefile.in not found. Running automake --add-missing."
          bash -c "automake --add-missing"
        fi
    - name: Configure
      run: ./configure
    - name: Make
      run: make
    - name: Test
      run: make check
    - name: Package
      run: make distcheck
