jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add missing files
        run: automake --add-missing
      - name: Configure
        run: ./configure
      - name: Build
        run: make
